import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import Layout from '../components/Layout/Layout'
import Panorama from '../components/Panorama/Panorama'
import Items from '../components/Items/Items'

import ShoppingCart from '../components/ShoppingCart/ShoppingCart';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <ShoppingCart />
          <Panorama />
          <Items />
        </Layout>
      </main>
    </>
  );
}
